import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI ChatBot",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#020617" },
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
  ],
};

// Minimal background/text values per theme, just enough to paint the
// correct colors before React hydrates. ThemeContext (client-side) takes
// over immediately after and applies the full variable set — this only
// prevents a flash of the wrong theme on reload.
const THEME_BOOT_SCRIPT = `
(function () {
  try {
    var CRITICAL = {
      midnight: { from: "#020617", via: "#0f172a", to: "#020617", text: "#f1f5f9" },
      snow:     { from: "#ffffff", via: "#f8fafc", to: "#ffffff", text: "#0f172a" },
      crimson:  { from: "#1a0508", via: "#2a0a10", to: "#1a0508", text: "#fdf2f2" },
      sky:      { from: "#eef7ff", via: "#e0f2fe", to: "#eef7ff", text: "#0c4a6e" },
      blossom:  { from: "#fff5fa", via: "#fce7f3", to: "#fff5fa", text: "#831843" },
      aurora:   { from: "#0b0a1a", via: "#140f2b", to: "#0b0a1a", text: "#f1eefc" }
    };
    var stored = localStorage.getItem("chatbot-theme");
    var theme = CRITICAL[stored] ? stored : "midnight";
    var t = CRITICAL[theme];
    var root = document.documentElement;
    root.dataset.theme = theme;
    root.style.setProperty("--bg-app-from", t.from);
    root.style.setProperty("--bg-app-via", t.via);
    root.style.setProperty("--bg-app-to", t.to);
    root.style.setProperty("--bg-solid", t.from);
    root.style.setProperty("--text-primary", t.text);
    root.style.backgroundColor = t.from;
  } catch (e) {}
})();
`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOT_SCRIPT }} />
      </head>
      <body
        suppressHydrationWarning
        className="min-h-full flex flex-col bg-[var(--bg-solid,#020617)] text-[var(--text-primary,#f1f5f9)]"
      >
        {children}
      </body>
    </html>
  );
}